name: master-actions
run-name: RELEASE
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Build
        run: |
          yarn install
          yarn build

      - name: Minio Deploy
        uses: marverlous811/minio-upload@v1.2.0
        with:
          endpoint: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: 'verv'
          local_path: './dist/*'
          remote_path: '/velez/'
          recursive: true
